export const homeItems = [
  {
    titulo: "Custom Cursor",
    descripcion: "",
    gif: "public/gifs/gestor-turnos.mp4",
    prototype: "/prototype/1",
  },
  {
    titulo: "Vanish Input",
    descripcion: "",
    gif: "https://cdn.jsdelivr.net/gh/franlopezmora/portfolio-assets@main/videos/vanish-input/vanish-input.mp4",
    webm: "https://cdn.jsdelivr.net/gh/franlopezmora/portfolio-assets@main/videos/vanish-input/vanish-input.webm",
    poster: "https://cdn.jsdelivr.net/gh/franlopezmora/portfolio-assets@main/videos/vanish-input/vanish-input-poster.jpg",
    prototype: "/prototype/2",
    playbackRate: 1.9,
  },
  {
    titulo: "Dark Mode Toggle",
    descripcion: "",
    gif: "https://cdn.jsdelivr.net/gh/franlopezmora/portfolio-assets@main/videos/dark-mode3/dark-mode3.mp4",
    webm: "https://cdn.jsdelivr.net/gh/franlopezmora/portfolio-assets@main/videos/dark-mode3/dark-mode3.webm",
    poster: "https://cdn.jsdelivr.net/gh/franlopezmora/portfolio-assets@main/videos/dark-mode3/dark-mode3-poster.jpg",
  },
  {
    titulo: "Gooey Tooltip",
    descripcion: "",
    gif: "https://cdn.jsdelivr.net/gh/franlopezmora/portfolio-assets@main/videos/gooey-tooltip/gooey-tooltip2.mp4",
    webm: "https://cdn.jsdelivr.net/gh/franlopezmora/portfolio-assets@main/videos/gooey-tooltip/gooey-tooltip2.webm",
    poster: "https://cdn.jsdelivr.net/gh/franlopezmora/portfolio-assets@main/videos/gooey-tooltip/gooey-tooltip2-poster.jpg",
    prototype: "/prototype/4",
  },
  {
    titulo: "Pill Nav Dock",
    descripcion: "",
    gif: "https://cdn.jsdelivr.net/gh/franlopezmora/portfolio-assets@main/videos/nav-bar/nav-dock.mp4",
    webm: "https://cdn.jsdelivr.net/gh/franlopezmora/portfolio-assets@main/videos/nav-bar/nav-dock.webm",
    poster: "https://cdn.jsdelivr.net/gh/franlopezmora/portfolio-assets@main/videos/nav-bar/nav-dock-poster.jpg",
    prototype: "/prototype/5",
  },
  {
    titulo: "Animated Checkbox",
    descripcion: "",
    gif: "https://cdn.jsdelivr.net/gh/franlopezmora/portfolio-assets@main/videos/animated-checkbox/animated-checkbox.mp4",
    webm: "https://cdn.jsdelivr.net/gh/franlopezmora/portfolio-assets@main/videos/animated-checkbox/animated-checkbox.webm",
    poster: "https://cdn.jsdelivr.net/gh/franlopezmora/portfolio-assets@main/videos/animated-checkbox/animated-checkbox-poster.jpg",
    prototype: "/prototype/6",
    titleColor: "dark",
    fecha: "Enero 2025"
  },
  {
    titulo: "Side Bar",
    descripcion: "",
    fecha: "Junio 2025",
    prototype: "/prototype/7",
    gif: "https://cdn.jsdelivr.net/gh/franlopezmora/portfolio-assets@main/videos/side-bar/side-bar.mp4",
    webm: "https://cdn.jsdelivr.net/gh/franlopezmora/portfolio-assets@main/videos/side-bar/side-bar2.webm",
    poster: "https://cdn.jsdelivr.net/gh/franlopezmora/portfolio-assets@main/videos/side-bar/side-bar-poster.jpg",
  },
  {
    titulo: "Animación de personaje",
    descripcion: "",
    gif: "",
    overlayPos: "top",
    titleColor: "dark",
    fecha: "Marzo 2025",
    essay: "/essay/crafting-cruma",
  },
  {
    titulo: "Sistema de Pruebas de Manejo",
    descripcion: "Backend con microservicios para gestionar pruebas de manejo",
    gif: "/src/images/Captura de pantalla 2025-09-02 224640.png",
    overlayPos: "top",
    titleColor: "dark",
    fecha: "Febrero 2025",
    essay: "/essay/crafting-tpi-backend",
  },
  {
    titulo: "Dashboard de pruebas",
    descripcion: "",
    gif: "",
    prototype: "View Prototype →",
    fecha: "Marzo 2025",
  }
];