export const homeItems = [
  {
    titulo: "Custom Cursor",
    descripcion: "",
    gif: "https://cdn.jsdelivr.net/gh/franlopezmora/portfolio-assets@main/videos/custom-cursor/custom-cursor.mp4",
    webm: "https://cdn.jsdelivr.net/gh/franlopezmora/portfolio-assets@main/videos/custom-cursor/custom-cursor.webm",
    poster: "https://cdn.jsdelivr.net/gh/franlopezmora/portfolio-assets@main/videos/custom-cursor/custom-cursor-poster.jpg",
    prototype: "/prototype/1",
    dateColor: "light",
    fecha: "Noviembre 2024",
  },
  {
    titulo: "Vanish Input",
    descripcion: "",
    gif: "https://cdn.jsdelivr.net/gh/franlopezmora/portfolio-assets@main/videos/vanish-input/vanish-input.mp4",
    webm: "https://cdn.jsdelivr.net/gh/franlopezmora/portfolio-assets@main/videos/vanish-input/vanish-input.webm",
    poster: "https://cdn.jsdelivr.net/gh/franlopezmora/portfolio-assets@main/videos/vanish-input/vanish-input-poster.jpg",
    prototype: "/prototype/2",
    playbackRate: 1.9,
    dateColor: "light",
    fecha: "Febrero 2025",
  },
  {
    titulo: "Dark Mode Toggle",
    descripcion: "",
    gif: "https://cdn.jsdelivr.net/gh/franlopezmora/portfolio-assets@main/videos/dark-mode3/dark-mode3.mp4",
    webm: "https://cdn.jsdelivr.net/gh/franlopezmora/portfolio-assets@main/videos/dark-mode3/dark-mode3.webm",
    poster: "https://cdn.jsdelivr.net/gh/franlopezmora/portfolio-assets@main/videos/dark-mode3/dark-mode3-poster.jpg",
    dateColor: "light",
    fecha: "Octubre 2024",
  },
  {
    titulo: "Gooey Tooltip",
    descripcion: "",
    gif: "https://cdn.jsdelivr.net/gh/franlopezmora/portfolio-assets@main/videos/gooey-tooltip/gooey-tooltip2.mp4",
    webm: "https://cdn.jsdelivr.net/gh/franlopezmora/portfolio-assets@main/videos/gooey-tooltip/gooey-tooltip2.webm",
    poster: "https://cdn.jsdelivr.net/gh/franlopezmora/portfolio-assets@main/videos/gooey-tooltip/gooey-tooltip2-poster.jpg",
    prototype: "/prototype/4",
    dateColor: "light",
    fecha: "Septiembre 2024",
  },
  {
    titulo: "Pill Nav Dock",
    descripcion: "",
    gif: "https://cdn.jsdelivr.net/gh/franlopezmora/portfolio-assets@main/videos/nav-bar/nav-dock.mp4",
    webm: "https://cdn.jsdelivr.net/gh/franlopezmora/portfolio-assets@main/videos/nav-bar/nav-dock.webm",
    poster: "https://cdn.jsdelivr.net/gh/franlopezmora/portfolio-assets@main/videos/nav-bar/nav-dock-poster.jpg",
    prototype: "/prototype/5",
    dateColor: "light",
    fecha: "Agosto 2024",
  },
  {
    titulo: "Animated Checkbox",
    descripcion: "",
    gif: "https://cdn.jsdelivr.net/gh/franlopezmora/portfolio-assets@main/videos/animated-checkbox/animated-checkbox.mp4",
    webm: "https://cdn.jsdelivr.net/gh/franlopezmora/portfolio-assets@main/videos/animated-checkbox/animated-checkbox.webm",
    poster: "https://cdn.jsdelivr.net/gh/franlopezmora/portfolio-assets@main/videos/animated-checkbox/animated-checkbox-poster.jpg",
    prototype: "/prototype/6",
    titleColor: "dark",
    fecha: "Enero 2025"
  },
  {
    titulo: "Side Bar",
    descripcion: "",
    dateColor: "light",
    fecha: "Diciembre 2024",
    prototype: "/prototype/7",
    gif: "https://cdn.jsdelivr.net/gh/franlopezmora/portfolio-assets@main/videos/side-bar/side-bar.mp4",
    webm: "https://cdn.jsdelivr.net/gh/franlopezmora/portfolio-assets@main/videos/side-bar/side-bar2.webm",
    poster: "https://cdn.jsdelivr.net/gh/franlopezmora/portfolio-assets@main/videos/side-bar/side-bar-poster.jpg",
  },
  {
    titulo: "Cruma",
    descripcion: "Planificador de horarios hecho por y para estudiantes",
    gif: "/images/Captura de pantalla 2025-09-04 155449.png",
    overlayPos: "top",
    dateColor: "light",
    fecha: "Agosto 2025",
    essay: "/essay/crafting-cruma",
  },
  {
    titulo: "Sistema de Pruebas de Manejo",
    descripcion: "Backend con microservicios para gestionar pruebas de manejo",
    gif: "/images/Captura de pantalla 2025-09-04 143046.png",
    overlayPos: "top",
    dateColor: "light",
    fecha: "Julio 2025",
    essay: "/essay/crafting-tpi-backend",
  },
];